name: Rotate Banner (Steam Assets)

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  rotate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_WRITE }}

      - name: Clone photos-steam (read)
        run: |
          git clone https://x-access-token:${{ secrets.GH_READ }}@github.com/luizangelomartins/photos-steam.git

      - name: Rotate banner inside repo
        run: |
          cd photos-steam

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          echo "=== CHECK DIR ==="
          ls -lah

          echo "=== BUILD QUEUE ==="
          find photos -type f > queue.txt

          echo "=== QUEUE CREATED ==="
          cat queue.txt

          shuf -o queue.txt queue.txt

          FILE=$(head -n 1 queue.txt)

          echo "Selected: $FILE"

          tail -n +2 queue.txt > tmp.txt
          mv tmp.txt queue.txt

          echo "$FILE" > state.txt
          echo "$(date -u)" >> state.txt

          cp "$FILE" banner.png

          echo "=== AFTER CHANGES ==="
          ls -lah

          git add -A

          git status

          git commit -m "rotate banner" || echo "No changes"

          git push https://x-access-token:${{ secrets.GH_WRITE }}@github.com/luizangelomartins/photos-steam.git
