name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: luizangelomartins
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%234da3ff&color_dots=%23151515,%23151515,%2379ff97,%2379ff97,%2379ff97

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output
